# Full reference https://github.com/foundry-rs/foundry/tree/master/config

[profile.default]
bytecode_hash = "none"
evm_version = "shanghai"
fuzz = { runs = 1_000 }
optimizer = true
optimizer_runs = 5000
out = "out"
solc = "0.8.26"

[profile.airdrops]
src = "airdrops"
test = "airdrops"

[profile.flow]
src = "flow"
test = "flow"

[profile.lockup]
src = "lockup"
test = "lockup"

[fmt]
bracket_spacing = true
int_types = "long"
line_length = 120
multiline_func_header = "all"
number_underscore = "thousands"
quote_style = "double"
tab_width = 4
wrap_comments = true

[rpc_endpoints]
sepolia = "${SEPOLIA_RPC_URL}"
